### PR TITLE
Added a test case that possibly identifies an issue regarding embedde…

### PR DESCRIPTION
**Pull request by brianchizhang**
…d objects not able to extract nullable fields

### CODE REVIEW

**Comment by brianchizhang** [comment]
Hi, we are trying to use the embedded object feature that's recently been added, and think it's awesome. But it seems to be failing to extract nullable fields. Please see the above PR for the test case. Thanks!

**Comment by jonbodner** [comment]
Thanks for the test case! I will take a look at it this weekend. I am pretty sure I know what's happening; there's a bit more work to do for complete support of structs within structs, including embedded structs.

**Comment by brianchizhang** [comment]
Great, thank you Jon!

**Comment by brianchizhang** [comment]
any update on this? (thx)

**Comment by jonbodner** [comment]
Didn't get a chance to take a look last weekend, checking now...

**Comment by jonbodner** [comment]
Merging in the test case, will fix next.

**Comment by jonbodner** [comment]
OK, I think I know what's going on. `sql.NullString` doesn't implement `sql.Scanner`; `*sql.NullString` does. 

I'm not sure why this is doing the right thing when the field isn't embedded, that's the odd part.

**Comment by jonbodner** [comment]
Figured it out. The test for the nil field was happening before the test to see if we needed to dive into the embedded struct, so the code was comparing the nil against the struct (which can't be nil).  Moving the tests around slightly fixes the problem. 

Your contributed test got me to clean up some other broken tests. Thanks! I'll have a new build out momentarily.

**Pull request merged**
